version: '2'
services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2025
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      odoo18_net:
        ipv4_address: 172.26.0.7

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "10018:8069"
      - "20018:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2025
    volumes:
      - ./etc:/etc/odoo
      - /mnt/extra-addons:/mnt/extra-addons  # قد يتعارض مع السطر السابق، راجع الملاحظة أدناه
      - /mnt/Database_Backup:/DatabaseB


    restart: always
    networks:
      odoo18_net:
        ipv4_address: 172.26.0.8

networks:
  odoo18_net:
    external: true
